### ISSUE TITLE
Option to manually enable it on a server?

### ISSUE THREAD

**Issue by kristofferpeterhansel** [sbine/TextualKappa#1]
Hey.

I'm running my connection to Twitch though a ZNC bouncer. Is there any chance this add-on could have an option to force it to be enabled for a specific server?

Right now it looks like it is using the server address to figure out if it should do it's thing or not. And obviously that isn't working when I have a different server in the middle.

**Comment by sbine** [comment]
Thanks for the suggestion! Adding a preferences pane for the plugin is on my to-do list; once that base work is done I'll be able to add server configuration options.

**Comment by sbine** [comment]
A preferences pane is available in [v0.0.2](https://github.com/sbine/TextualKappa/releases/tag/v0.0.2), and lets you manually enable the plugin on specified servers.
