### ISSUE TITLE
Add .xcodeproj

### ISSUE THREAD

**Issue by iamthad** [sbine/TextualKappa#2]
Could you please add the .xcodeproj file so other people can easily load the project?

**Comment by sbine** [comment]
Thanks for the reminder! I'll definitely add the .xcodeproj as part of my next feature push.

**Comment by iamthad** [comment]
Looks like you updated for Textual 6 recently. Could you add the .xcodeproj while the plugin is still on your mind?

**Comment by sbine** [comment]
Yep, it's been added now. Thanks!
