### ISSUE TITLE
Plugin is broken on macOS Sierra

### ISSUE THREAD

**Issue by sbine** [sbine/TextualKappa#3]
I've received several reports that the plugin is broken on macOS Sierra.

One of the bug reporters mentioned he had tweaked the Xcode project file to make it work; once he's sent it over I'd really appreciate any help verifying that the issue is fixed as I don't currently have access to a machine with Sierra.

**Comment by Hiramas** [comment]
I am running Sierra, if you send the fixed .bundle to me, I'll test if it works.
Though I can only respond with "works" or "does not work" due to lack of coding experience.

**Comment by sbine** [comment]
Thanks! I'm waiting to hear back; I'll let you know when I have a test build available.

**Comment by Stoopler** [comment]
I'll email you what I have later tonight when I'm back on my laptop.  I have the main "functionality" working, but if I remember right trying to go to the preferences pane crashes the client.

The twitch.tv API also now requires a client-id to be passed, so a setting option would probably need to be added to allow people to add their own appid to make API calls.

**Comment by sbine** [comment]
@Hiramas I have an updated bundle [available here](https://sarabine.com/TextualKappa.bundle.zip), please let me know if you run into any issues. I wasn't able to reproduce the preferences pane crash on Yosemite.
@stapler2025 thank you for notifying me about the Client-ID requirement 👍

**Comment by Hiramas** [comment]
Hey, I tested it. Moving this version into the "Extensions" folder crashes the client on startup.
Are there logfiles I can provide?

**Comment by sbine** [comment]
Thanks, I was able to get an old machine updated to Sierra and reproduced the crash issue. I replaced the linked bundle with a patched version, would you mind giving it another shot? If it still crashes, please email me at the address listed on my profile and we can dig through some logs.

**Comment by Hiramas** [comment]
No crash with this version.
The emotes work when coming from twitch. 
I don't know if that is a natural limitation but when you write the emote in textual it shows as text in the client. Comes through as an emote in twitch chat itself, though.

**Comment by sbine** [comment]
Yeah, supporting emotes in sent text is on the to-do list. Unfortunately it has to be handled completely differently than received emotes--the Twitch server tells you exactly where emotes are in received messages, but there is no such information available in sent messages.
Thanks for verifying this test build! It's now available as [v0.0.2](https://github.com/sbine/TextualKappa/releases/tag/v0.0.2).
