### ISSUE TITLE
OSX 10.13.3, Textual 7.0.8, ZNC bouncer -- doesn't seem to be working?

### ISSUE THREAD

**Issue by c17r** [sbine/TextualKappa#6]
Hello, very excited about this plugin.  System is above, I followed the install instructions and restarted Textual but I see no preference panel and chat hasn't changed.

Not sure which part of my system might be causing the problem.

**Comment by sbine** [comment]
Any chance you meant 10.13.3? 10.3.3 is Panther which is pretty old. Either way, the plugin will likely need updates for High Sierra.

**Comment by c17r** [comment]
Yes, I meant High Sierra :)

**Comment by rennsport** [comment]
Yeah I also have the same issue. I'm running macOS 10.13.3 and Textual 7.0.8.

**Comment by sbine** [comment]
I have a computer running High Sierra now, so should be able to take a look at this pretty soon.

**Comment by iiiGerardoiii** [comment]
wait @c17r how did you fix it?

**Comment by c17r** [comment]
Didn't, just closing it out

**Comment by sbine** [comment]
Apologies for never getting to this, I haven't used Twitch in a few years 😢

If anyone is interested in taking over plugin maintenance, feel free to shoot me an email (address on my profile)
